# Generated by Django 6.0.3 on 2026-03-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sentiment_distribution', models.JSONField(default=dict)),
                ('weighted_sentiment_score', models.FloatField(default=0.0)),
                ('top_keywords', models.JSONField(default=list)),
                ('topic_clusters', models.JSONField(default=list)),
                ('detected_pain_points', models.JSONField(default=list)),
                ('detected_questions', models.JSONField(default=list)),
                ('creator_recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=255)),
                ('like_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('is_question', models.BooleanField(default=False)),
                ('video_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='analyzer.videoanalysis')),
            ],
        ),
    ]
