# Generated by Django 6.0.3 on 2026-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='total_comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
